// Unicode emojis work everywhere. To use your own, upload them as application emojis in the
// Discord Developer Portal and replace a value with '<:name:id>' (or '<a:name:id>' if animated).
export const emojis = {
  previous: '⏮️',
  pause: '⏸️',
  resume: '▶️',
  skip: '⏭️',
  stop: '⏹️',
  shuffle: '🔀',
  loop: '🔁',
  loopTrack: '🔂',
  autoplay: '♾️',
  queue: '📜',
  commands: '📖',
  sound: '🎛️',
  lyrics: '🎤',
  volumeDown: '🔉',
  volumeUp: '🔊',
  back: '◀️',
  forward: '▶️',
  refresh: '🔄',
  clear: '🧹',
  replay: '↩️',
  leave: '👋',
  website: '🌐',
  invite: '➕',
  code: '📦',
  support: '💬',
  playing: '▶️',
  paused: '⏸️',
  live: '🔴',
};
